version: '3.5'
services:
  prime:
    build: 
      context: ./core
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    image: phucnguyendekttek/prime:${PRIME_TAG:-2.0.0}
    container_name: prime
  prime-front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API: ${REACT_APP_API:-http://localhost:8080}
    ports:
    - "80:80"
    image: phucnguyendekttek/prime-front:${PRIME_FRONT_TAG:-2.0.0}
    container_name: prime-front
